ALTER TABLE agunan
-- Alamat Lanjutan
ADD COLUMN IF NOT EXISTS rt_rw VARCHAR(50),
ADD COLUMN IF NOT EXISTS kelurahan VARCHAR(100),
ADD COLUMN IF NOT EXISTS kabupaten VARCHAR(100),
-- Batas Tanah
ADD COLUMN IF NOT EXISTS batas_utara VARCHAR(100),
ADD COLUMN IF NOT EXISTS batas_selatan VARCHAR(100),
ADD COLUMN IF NOT EXISTS batas_timur VARCHAR(100),
ADD COLUMN IF NOT EXISTS batas_barat VARCHAR(100),
-- Bentuk dan Ukuran Tanah
ADD COLUMN IF NOT EXISTS bentuk_tanah VARCHAR(50),
ADD COLUMN IF NOT EXISTS permukaan_tanah VARCHAR(50),
ADD COLUMN IF NOT EXISTS akses_jalan VARCHAR(100),
ADD COLUMN IF NOT EXISTS jenis_jalan VARCHAR(50),
-- Struktur Bangunan
ADD COLUMN IF NOT EXISTS lantai_bangunan VARCHAR(50),
ADD COLUMN IF NOT EXISTS rangka_atap VARCHAR(50),
ADD COLUMN IF NOT EXISTS penutup_atap VARCHAR(50),
ADD COLUMN IF NOT EXISTS dinding VARCHAR(50),
ADD COLUMN IF NOT EXISTS fasilitas_listrik VARCHAR(50),
ADD COLUMN IF NOT EXISTS fasilitas_air VARCHAR(50);
